### ISSUE TITLE
Automatically label new items will be unchecked every time you open zotero

### ISSUE THREAD

**Issue by 784494706** [Dominic-DallOsto/zotero-reading-list#16]
Automatically label new items will be unchecked every time I open zotero. I am not sure whether this is the author's setting or a problem with my software settings.

**Comment by Dominic-DallOsto** [comment]
Thanks for the info. This was a bug but should be fixed in the updated version of the plugin for Zotero 7 [here](https://github.com/Dominic-DallOsto/zotero-reading-list/releases/tag/v1.0.0-beta).

If there's enough demand I might try and backport the fixes for older versions of Zotero - let me know!
