### ISSUE TITLE
The auto label "New" is applied as text regardless of "show only icon" selected

### ISSUE THREAD

**Issue by helsingi** [Dominic-DallOsto/zotero-reading-list#44]
When new items are added and the option to auto add the label "New" is checked, the label "New" is literally applied regardless of other options such as that I chose to view only icons and no text.
![Screenshot 2024-08-02 130938](https://github.com/user-attachments/assets/9fc22860-1391-4cae-8f4d-c4879107150c)
![Screenshot 2024-08-02 131131](https://github.com/user-attachments/assets/91fe3672-478d-42be-89a3-a70abe42416f)

**Comment by Dominic-DallOsto** [comment]
Ahh, thanks for the detailed error report!

This is because the status that new items are automatically set to is currently fixed to `New`, but status names are case sensitive - so `New` doesn't match your read status `new`. Therefore `New` isn't a valid read status at all and so doesn't get formatted properly.

**Comment by Dominic-DallOsto** [comment]
Hopefully this new release solves the problem for you!
